name = "hex-poly-z-mathlib"
defaultTargets = ["HexPolyZMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "385df1df6b2667aeb001b6b781f7109943de243b"

[[require]]
name = "HexHensel"
git = "https://github.com/leanprover/hex-hensel.git"
rev = "67e940994ef10106a47b03a9d63ff8cd4a7a7daf"

[[require]]
name = "HexPolyMathlib"
git = "https://github.com/leanprover/hex-poly-mathlib.git"
rev = "a9eb9de8c92b96f57660d02c468f9f8622066641"

[[require]]
name = "HexModArithMathlib"
git = "https://github.com/leanprover/hex-mod-arith-mathlib.git"
rev = "5aa0aa69b47c153189d708c3047aa294a594113f"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexPolyZMathlib"
