name = "hex-poly-z-mathlib"
defaultTargets = ["HexPolyZMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "7d7fdebb1bde00648a951177e3042a3ffbb2a8ea"

[[require]]
name = "HexHensel"
git = "https://github.com/leanprover/hex-hensel.git"
rev = "604853baa6453ac620908f743cb2d736073a0868"

[[require]]
name = "HexPolyMathlib"
git = "https://github.com/leanprover/hex-poly-mathlib.git"
rev = "5897ba144a95f929e975c3eeb5a5c5a956f8e2ba"

[[require]]
name = "HexModArithMathlib"
git = "https://github.com/leanprover/hex-mod-arith-mathlib.git"
rev = "0aab0ebded5d539f581252e74540cbba48e6d89b"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.33.0-rc1"

[[lean_lib]]
name = "HexPolyZMathlib"
