name = "hex-poly-z-mathlib"
defaultTargets = ["HexPolyZMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "037df2d4b50602d07892e7591547c4b641b03c63"

[[require]]
name = "HexHensel"
git = "https://github.com/leanprover/hex-hensel.git"
rev = "e9cdca38baa5b0c9e6449300715cb4defc342f9c"

[[require]]
name = "HexPolyMathlib"
git = "https://github.com/leanprover/hex-poly-mathlib.git"
rev = "d4bbb82b87704d3016c6c1d822ae1f77c793958a"

[[require]]
name = "HexModArithMathlib"
git = "https://github.com/leanprover/hex-mod-arith-mathlib.git"
rev = "5aa0aa69b47c153189d708c3047aa294a594113f"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexPolyZMathlib"
